### ISSUE TITLE
Unable to get author of message

### ISSUE THREAD

**Issue by Aya-Komichi** [Arthur-Damasceno/ruvolt#9]
So as a standard I acquired while coding discord bots, I would prefer if my bot didn't answer to other bots.
However this reveals to be quite difficult to achieve since it seems the cache never has the message author stored.

This is the piece of code I have to attempt to get the message author from the cache.
```rust
ctx.cache.user(&msg.author_id).await
```
In reality, this always seems to return `None`. I noticed a trait for the Cache, but I'm not quite sure if that is being used or not.

Since I'm a rust noob, I'm almost certainly missing something. Can you help me again?

**Comment by arthurhoz** [comment]
If it is returning `None` it is because the user is not stored in the cache. They are only stored when the bot is started and a `Ready` event is received with the data. The API has been updated, I'm not sure if users just aren't sent in that event or something has changed, sorry for the lack of maintenance, maybe I'll get back to doing something this week.

In case you really don't want to respond to bots, you can fetch the user in the api and check.

```rust
if let Ok(user) = User::fetch(&cx, &msg.author_id).await {
    if user.is_bot() {
       return;
    }
}
```

I don't recommend doing this, because of latency and the new rate limits.

**Comment by Aya-Komichi** [comment]
> If it is returning None it is because the user is not stored in the cache.

That I pretty much had expected. Even thou I did see the code that is supposed to update the cache and where that is being called, I am not entirely sure it is ever executed.

> The API has been updated, I'm not sure if users just aren't sent in that event or something has changed, sorry for the lack of maintenance, maybe I'll get back to doing something this week.

Good luck with that. I could try to help if I have the time, but no guarantees. XD

> I don't recommend doing this, because of latency and the new rate limits.

Ye, not really gonna bother much about it then, it's not a current top priority. I have a working version that doesn't bother with the users being or not bots.
